name: font_awesome_flutter_example
description: The Font Awesome Flutter Gallery

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter:
    path: ../

flutter:
  uses-material-design: true

  # In order to use font_awesome_flutter in your own app, be sure to
  # include the following font declaration in your pubspec.yaml
  fonts:
    - family: FontAwesome # Do not change!
      fonts:
        - asset: packages/font_awesome_flutter/fonts/fontawesome-webfont.woff