name: font_awesome_flutter
description: The Font Awesome Icon pack available as Flutter Icons
author: Brian Egan <brian@brianegan.com>
homepage: https://github.com/brianegan/font_awesome_flutter
version: 4.7.3

dependencies:
  flutter:
    sdk: flutter

flutter:
  fonts:
    - family: FontAwesome
      fonts:
        - asset: assets/fontawesome.woff
