name: font_awesome_flutter
author: Brian Egan <brian@brianegan.com>
description: The Font Awesome Icon pack available as Flutter Icons
homepage: https://github.com/brianegan/font_awesome_flutter
version: 4.7.1

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
